const ListBooks = [
  {
    id: 1,
    title: "Atomic Habits",
    img: "atomic.jpg",
    author: "James Clear",
    is_free: true,
    sinopsis: "Panduan membangun kebiasaan baik dan menghancurkan kebiasaan buruk.",
    rating: 4.8,
    views: 1200,
  },
  {
    id: 2,
    title: "Rich Dad Poor Dad",
    img: "richdad.jpg",
    author: "Robert Kiyosaki",
    is_free: false,
    sinopsis: "Belajar mindset keuangan dari dua sudut pandang berbeda.",
    rating: 4.7,
    views: 980,
  },
  {
    id: 3,
    title: "The Psychology of Money",
    img: "money.jpg",
    author: "Morgan Housel",
    is_free: true,
    sinopsis: "Cara orang berpikir tentang uang dan keputusan finansial.",
    rating: 4.6,
    views: 870,
  },
  {
    id: 4,
    title: "Think and Grow Rich",
    img: "think.jpg",
    author: "Napoleon Hill",
    is_free: false,
    sinopsis: "Buku klasik tentang kesuksesan dan mindset kaya.",
    rating: 4.5,
    views: 760,
  },
  {
    id: 5,
    title: "Deep Work",
    img: "deepwork.jpg",
    author: "Cal Newport",
    is_free: true,
    sinopsis: "Cara fokus dan bekerja secara mendalam.",
    rating: 4.7,
    views: 650,
  },
  {
    id: 6,
    title: "Ikigai",
    img: "ikigai.jpg",
    author: "Hector Garcia",
    is_free: false,
    sinopsis: "Rahasia hidup panjang dan bahagia ala Jepang.",
    rating: 4.6,
    views: 720,
  },
];

export default ListBooks;